---
language: ruby
matrix:
  include:
  - rvm: 2.4.9
    gemfile: gemfiles/rails_4.2.11.1.gemfile
    env: BUNDLER_VERSION=1.17.3 RAILS_ENV=test
  - rvm: 2.5.7
    gemfile: gemfiles/rails_4.2.11.1.gemfile
    env: BUNDLER_VERSION=1.17.3 RAILS_ENV=test
  - rvm: 2.6.5
    gemfile: gemfiles/rails_4.2.11.1.gemfile
    env: BUNDLER_VERSION=1.17.3 RAILS_ENV=test
  - rvm: 2.4.9
    gemfile: gemfiles/rails_5.2.3.gemfile
    env: BUNDLER_VERSION=1.17.3 RAILS_ENV=test
  - rvm: 2.5.7
    gemfile: gemfiles/rails_5.2.3.gemfile
    env: BUNDLER_VERSION=1.17.3 RAILS_ENV=test
  - rvm: 2.6.5
    gemfile: gemfiles/rails_5.2.3.gemfile
    env: BUNDLER_VERSION=1.17.3 RAILS_ENV=test
before_install:
- gem uninstall -i $(rvm gemdir)@global -ax bundler || true
- gem install bundler -v "$BUNDLER_VERSION"
install: bundle install --retry=3
script:
- bundle exec rake dummy:prepare
- bundle exec rspec
- bundle exec rubocop
addons:
  code_climate:
    repo_token: '085c9fc58ac3efcd9a8b311ee77bcec0b5c048575cde8a2234f7c63550910969'
