---
language: ruby
matrix:
  include:
  - rvm: 2.5.7
    gemfile: gemfiles/rails____6.0.0_activeadmin_2.4.0.gemfile
  - rvm: 2.5.7
    gemfile: gemfiles/rails____6.0.0_activeadmin_2.3.1.gemfile
  - rvm: 2.5.7
    gemfile: gemfiles/rails____5.2.3_activeadmin_2.3.1.gemfile
  - rvm: 2.5.7
    gemfile: gemfiles/rails____4.2_activeadmin_1.4.3.gemfile
  - rvm: 2.5.7
    gemfile: gemfiles/rails____5.2.3_activeadmin_2.4.0.gemfile
  - rvm: 2.6.5
    gemfile: gemfiles/rails____6.0.0_activeadmin_2.4.0.gemfile
  - rvm: 2.6.5
    gemfile: gemfiles/rails____6.0.0_activeadmin_2.3.1.gemfile
  - rvm: 2.6.5
    gemfile: gemfiles/rails____5.2.3_activeadmin_2.3.1.gemfile
  - rvm: 2.6.5
    gemfile: gemfiles/rails____4.2_activeadmin_1.4.3.gemfile
  - rvm: 2.6.5
    gemfile: gemfiles/rails____5.2.3_activeadmin_2.4.0.gemfile
before_install:
- gem uninstall -i $(rvm gemdir)@global -ax bundler || true
- gem install bundler -v 1.17.3
env: RAILS_ENV=test
install: bundle install --retry=3
script:
- bundle exec rake dummy:prepare
- bundle exec rspec
- bundle exec rubocop
addons:
  code_climate:
    repo_token: '085c9fc58ac3efcd9a8b311ee77bcec0b5c048575cde8a2234f7c63550910969'
